name: geopython
channels:
  - conda-forge
dependencies:
  - python=3.9
  - geopandas
  - jupyter
  - sqlalchemy
  - psycopg2
  - geoalchemy2
  - tqdm
  - openpyxl
  - pip
  - pip:
    - aiohttp
    - aiosignal
    - async-timeout
    - attrs
    - beautifulsoup4
    - certifi
    - charset
    - frozenlist
    - idna
    - multidict
    - PyYAML
    - pyyaml
    - requests
    - soupsieve
    - tqdm
    - typing-extensions
    - urllib3
    - yarl
